CREATE DATABASE IF NOT EXISTS STUDENTS;

USE STUDENTS;

CREATE TABLE CLASS_X (ID INT PRIMARY KEY, NAME VARCHAR(50), AGE INT NOT NULL);

INSERT INTO CLASS_X(ID, NAME, AGE) VALUES(1, "VEDANT GANESH YETEKAR", 21), (2, "ADVAITNATH RAM LIKHITKAR", 21);
INSERT INTO CLASS_X VALUES(3, "RAM", 1);

SELECT * FROM CLASS_X;

SHOW DATABASES;
SHOW TABLES;

DROP DATABASE IF EXISTS STUDENTS;