CREATE DATABASE IF NOT EXISTS TEMP;

USE TEMP;

CREATE TABLE PAIRS(A INT, B INT);

INSERT INTO PAIRS(A, B) VALUES(1, 2), (2, 4), (2, 1), (3, 2), (4, 2), (5, 6), (6, 5), (7, 8);

SELECT * FROM PAIRS;

SELECT P1.* FROM PAIRS P1 LEFT JOIN PAIRS P2 ON P1.A=P2.B AND P1.B=P2.A WHERE P2.A IS NULL OR P1.A<P2.A;

SELECT * FROM PAIRS P1 WHERE NOT EXISTS
(SELECT * FROM PAIRS P2 WHERE P1.B=P2.A AND P1.A=P2.B AND P1.A > P2.A);