CREATE DATABASE IF NOT EXISTS TEST;

USE TEST;

CREATE TABLE TEST_TABLE1(ID INT NOT NULL);
CREATE TABLE TEST_TABLE2(ID INT UNIQUE);
CREATE TABLE TEST_TABLE3(ID INT PRIMARY KEY);
CREATE TABLE TEST_TABLE4(ID INT, PRIMARY KEY(ID));
CREATE TABLE TEST_TABLE5(ID INT, NAME VARCHAR(50), SALARY INT DEFAULT 200000, AGE INT, PRIMARY KEY(ID, NAME), CONSTRAINT ISADULT CHECK (AGE>=18));

INSERT INTO TEST_TABLE1(ID) VALUES(1);
INSERT INTO TEST_TABLE1(ID) VALUES(2);

INSERT INTO TEST_TABLE2(ID) VALUES(1);
INSERT INTO TEST_TABLE2(ID) VALUES(2);

INSERT INTO TEST_TABLE3(ID) VALUES(1);
INSERT INTO TEST_TABLE3(ID) VALUES(2);

INSERT INTO TEST_TABLE4(ID) VALUES(1);
INSERT INTO TEST_TABLE4(ID) VALUES(2);

INSERT INTO TEST_TABLE5(ID, NAME, SALARY, AGE) VALUES(1, "VEDANT YETEKAR", 200000, 21);
INSERT INTO TEST_TABLE5(ID, NAME, AGE) VALUES(2, "ADVAITNATH LIKHITKAR", 21);

SELECT * FROM TEST_TABLE1;
SELECT * FROM TEST_TABLE2;
SELECT * FROM TEST_TABLE3;
SELECT * FROM TEST_TABLE4;
SELECT * FROM TEST_TABLE5;

DROP DATABASE IF EXISTS TEST;