USE ORG;

SELECT * FROM WORKER;
SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%ON%';
SELECT * FROM WORKER WHERE LAST_NAME LIKE '%E_AR%';
SELECT * FROM WORKER ORDER BY SALARY ASC;
SELECT * FROM WORKER ORDER BY SALARY DESC;
SELECT DISTINCT(DEPARTMENT) AS DEPARTMENTS FROM WORKER;

-- GROUP BY: USED WITH AGGREGATION FUNCTIONS LIKE MENTIONED BELOW
-- COUNT, SUM, MAXIMUM, MINIMUM, AVERAGE

SELECT DEPARTMENT FROM WORKER GROUP BY DEPARTMENT;

SELECT DEPARTMENT, COUNT(DEPARTMENT) AS TOTAL_EMPLOYEES FROM WORKER GROUP BY DEPARTMENT;
SELECT DEPARTMENT, COUNT(*) AS TOTAL_EMPLOYEES FROM WORKER GROUP BY DEPARTMENT;

SELECT DEPARTMENT, AVG(SALARY) AS 'AVERAGE SALARY' FROM WORKER GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MIN(SALARY) AS 'MINIMUM SALARY' FROM WORKER GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MAX(SALARY) AS 'MAXIMUM SALARY' FROM WORKER GROUP BY DEPARTMENT;

SELECT DEPARTMENT, SUM(SALARY) AS 'TOTAL SALARY PAID' FROM WORKER GROUP BY DEPARTMENT;

-- WHERE USED WITH SELECT
-- HAVING USED WITH GROUP BY

SELECT DEPARTMENT, COUNT(DEPARTMENT) AS 'TOTAL EMPLOYEES' FROM WORKER GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT)>2;





