DROP DATABASE IF EXISTS ECOMMERCE;
CREATE DATABASE IF NOT EXISTS ECOMMERCE;
USE ECOMMERCE;

CREATE TABLE CUSTOMER(ID INT PRIMARY KEY AUTO_INCREMENT,
USER_NAME VARCHAR(255) UNIQUE,
BALANCE LONG DEFAULT(550) NOT NULL, CONSTRAINT ACC_BALANCE_CHK CHECK(BALANCE>500));

INSERT INTO CUSTOMER(ID, USER_NAME, BALANCE) VALUES(1, 'johndoe', 10000), (2, 'parthy9', 5000000000);

CREATE TABLE ORDERS(ID INT PRIMARY KEY, CUST_ID INT, 
ITEM VARCHAR(255), FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE);

INSERT INTO ORDERS(ID, CUST_ID, ITEM) VALUES(1, 1, 'Chole Bhature');
INSERT INTO ORDERS(ID, CUST_ID, ITEM) VALUES(2, 2, 'Chesse Pizza');

SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

-- DUPLICATES NOT ALLOWED
-- INSERT INTO CUSTOMER(ID, USER_NAME) VALUES(3, 'vedanty1');

INSERT INTO CUSTOMER(USER_NAME, BALANCE) VALUES('vedanty1', 10000000000000000);

SELECT * FROM CUSTOMER;

-- AN ATTRIBUTE CAN BE PRIMARY KEY AND FOREIGN KEY BOTH