-- JOINS
USE ECOMMERCE;
SHOW TABLES;

INSERT INTO CUSTOMER_ORDERS(ID, CUST_ID, ITEM, TOTAL_AMOUNT)
VALUES(3, 4, "Margherita", 350), 
(4, 6, "Veg Biryani", 150), 
(5, 5, "Chowmein", 200);

SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER_ORDERS;

-- INNER JOIN
SELECT C.ID, O.CUST_ID, C.USER_NAME, O.ITEM, C.BALANCE, O.TOTAL_AMOUNT 
FROM CUSTOMER AS C INNER JOIN CUSTOMER_ORDERS AS O ON C.ID = O.CUST_ID;

SELECT C.ID, O.CUST_ID, C.USER_NAME, O.ITEM, C.BALANCE, O.TOTAL_AMOUNT 
FROM CUSTOMER AS C INNER JOIN CUSTOMER_ORDERS AS O ON C.ID = O.CUST_ID WHERE O.TOTAL_AMOUNT>=1000;

-- LEFT JOIN
SELECT C.ID, O.ID, C.USER_NAME, O.ITEM, C.BALANCE, O.TOTAL_AMOUNT 
FROM CUSTOMER AS C LEFT JOIN CUSTOMER_ORDERS AS O ON C.ID = O.CUST_ID;

-- RIGHT JOIN
SELECT C.ID, O.ID, C.USER_NAME, O.ITEM, C.BALANCE, O.TOTAL_AMOUNT 
FROM CUSTOMER AS C RIGHT JOIN CUSTOMER_ORDERS AS O ON C.ID = O.CUST_ID;

-- CROSS JOIN
SELECT C.ID, O.ID, C.USER_NAME, O.ITEM, C.BALANCE, O.TOTAL_AMOUNT FROM
CUSTOMER AS C CROSS JOIN CUSTOMER_ORDERS AS O;

-- CAN WE USE INNER JOIN WITHOUT USING JOIN KEYWORD?
-- YES
SELECT * FROM CUSTOMER, CUSTOMER_ORDERS WHERE CUSTOMER.ID=CUSTOMER_ORDERS.CUST_ID;

