DROP DATABASE IF EXISTS ABC_COMPANY;
CREATE DATABASE IF NOT EXISTS ABC_COMPANY;

USE ABC_COMPANY;

CREATE TABLE USA_EMP_DETAILS
(EMP_ID INT PRIMARY KEY UNIQUE, EMP_NAME VARCHAR(255) NOT NULL, EMP_ROLE VARCHAR(255));

CREATE TABLE IN_EMP_DETAILS
(EMP_ID INT PRIMARY KEY UNIQUE, EMP_NAME VARCHAR(255) NOT NULL, EMP_ROLE VARCHAR(255));

INSERT INTO USA_EMP_DETAILS(EMP_ID, EMP_NAME, EMP_ROLE) 
VALUES(1, 'John', 'Engineer'),
(2, 'Joseph', 'Salesman'),
(3, 'Christine', 'Manager'),
(4, 'Lisa', 'Salesman'),
(5, 'Yusuf', 'Engineer');

INSERT INTO IN_EMP_DETAILS(EMP_ID, EMP_NAME, EMP_ROLE) 
VALUES(3, 'Christine', 'Manager'),
(6, 'Raghav', 'Salesman'),
(7, 'Parth', 'Engineer');

SELECT * FROM USA_EMP_DETAILS;
SELECT * FROM IN_EMP_DETAILS;

-- UNION
SELECT * FROM USA_EMP_DETAILS UNION SELECT * FROM IN_EMP_DETAILS;

SELECT * FROM USA_EMP_DETAILS WHERE EMP_ROLE='Salesman'
UNION
SELECT * FROM IN_EMP_DETAILS WHERE EMP_ROLE='Salesman';

-- INTERSECT
SELECT USA.* FROM USA_EMP_DETAILS AS USA INNER JOIN IN_EMP_DETAILS AS IND USING(EMP_ID);

-- MINUS
SELECT USA.* FROM USA_EMP_DETAILS AS USA LEFT JOIN IN_EMP_DETAILS AS IND 
USING(EMP_ID) WHERE IND.EMP_ID IS NULL;

