USE ECOMMERCE;

SHOW TABLES;

SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER_ORDERS;

SELECT * FROM CUSTOMER WHERE ID IN 
(SELECT CUST_ID FROM CUSTOMER_ORDERS);

SELECT * FROM CUSTOMER WHERE BALANCE >=
(SELECT AVG(BALANCE) FROM CUSTOMER)/1000000000;

SELECT MAX(TOTAL_AMOUNT) FROM (SELECT * FROM CUSTOMER_ORDERS WHERE TOTAL_AMOUNT>=550) 
AS DERIVED_TABLE;

SELECT * FROM CUSTOMER AS C1 WHERE 3 = (
SELECT COUNT(C2.BALANCE) FROM CUSTOMER AS C2 WHERE C2.BALANCE<C1.BALANCE
)