USE ECOMMERCE;

SELECT * FROM CUSTOMER;

CREATE VIEW ABSTRACT_CUSTOMER_DETAILS AS SELECT ID, USER_NAME FROM CUSTOMER;

SELECT * FROM ABSTRACT_CUSTOMER_DETAILS;

ALTER VIEW ABSTRACT_CUSTOMER_DETAILS AS SELECT USER_NAME FROM CUSTOMER;

SELECT * FROM ABSTRACT_CUSTOMER_DETAILS;

DROP VIEW IF EXISTS ABSTRACT_CUSTOMER_DETAILS;

SELECT * FROM ABSTRACT_CUSTOMER_DETAILS;