CREATE DATABASE IF NOT EXISTS STUDENTS;

USE STUDENTS;

CREATE TABLE CLASS_X (ID INT, NAME VARCHAR(50));

INSERT INTO CLASS_X(ID, NAME) VALUES(1, "VEDANT GANESH YETEKAR");
INSERT INTO CLASS_X(ID, NAME) VALUES(1, "ADVAITNATH RAM LIKHITKAR");

SELECT * FROM CLASS_X;

SHOW DATABASES;
SHOW TABLES;

DROP DATABASE IF EXISTS STUDENTS;