CREATE DATABASE SATYUGA;

USE SATYUGA;

CREATE TABLE LORDS(ID INT PRIMARY KEY, NAME VARCHAR(50));

INSERT LORDS(ID, NAME) VALUES(1, "RAM"), (2, "SHIVA"), (3, "GANESHA"), (4, "VISHNU");
INSERT LORDS VALUES(5, "DURGA");

SELECT * FROM LORDS;